### ISSUE TITLE
Unable to build with 0.8.10

### ISSUE THREAD

**Issue by knepe** [LeonHartley/Coerce-rs#32]
Hey,

I'm using latest coerce version, but I'm getting a build error:

`error[E0425]: cannot find value VERSION_3_2_0 in crate protobuf
  --> /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/coerce-0.8.10/src/remote/net/proto/network.rs:26:49
   |
26 | const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;
   |                                                 ^^^^^^^^^^^^^ help: a constant with a similar name exists: VERSION_3_3_0
   |
   |
7  | pub const VERSION_3_3_0: () = ();
   | --------------------------- similarly named constant VERSION_3_3_0 defined here`

I tried checking if I had any other dependency on protobuf 3.3.0 but it looks like it comes from coerce if I do `cargo tree`

**Comment by knepe** [comment]
It compiles if I add `protobuf = "=3.2.0"` to my Cargo.toml

**Comment by LeonHartley** [comment]
That's interesting! Coerce does not depend on protobuf 3.3.0, so you may have another dependency in your project that uses it.

**Comment by AdriaanPrinsloo** [comment]
@knepe  I have the same issue with my CI. I suspect the problem is that protobuf does exact version checks in generated files, but if we don't include the specific "=3.2.0" version when you bring it in, cargo will automatically get the latest 3.X.X version if it's available, causing a version mismatch when it compiles the generated file.  @LeonHartley I suspect we don't see this issue in the Coerce codebase because we version control the Cargo.lock file.

**Comment by LeonHartley** [comment]
Thanks guys, @AdriaanPrinsloo has hopefully resolved this, I will aim to release 8.11 this evening.

**Comment by AdriaanPrinsloo** [comment]
@LeonHartley, Is there anything I can do to help get 8.11 out the door?

**Comment by LeonHartley** [comment]
Sorry for the delay, it was a very busy week for me. I have published 0.8.11 now!

**Comment by AdriaanPrinsloo** [comment]
No worries man, I didn't mean to put any pressure on you, just thought if I could help in some way, I'd offer.  Thanks for the release, that's wonderful!

**Comment by LeonHartley** [comment]
@knepe Please could you try the latest release (0.8.11) and let me know that this issue is now resolved? :)

**Comment by knepe** [comment]
@LeonHartley @AdriaanPrinsloo Just tested, works perfect. Thanks guys :)
